# Dockerfile.manufacturer
FROM python:3.10-slim

WORKDIR /app

# Copy files to the container
COPY manufacturer_server.py requirements.txt /app/
COPY sbom_converted.json /app/

RUN pip install -r requirements.txt

EXPOSE 5000

CMD ["python", "manufacturer_server.py"]
